/**
 * Seed script for credit_cards table.
 * Run with: npx tsx lib/credit-cards-seed.ts
 */

import { getSupabaseAdmin } from "./supabase";

interface CreditCardSeed {
  id: string;
  name: string;
  issuer: string;
  network: string;
  annual_fee: number;
  rewards_program: string;
  rewards_value_cpp: number;
  earn_rates: Record<string, number>;
  sign_up_bonus_value: number;
  sign_up_bonus_spend: number;
  sign_up_bonus_days: number;
  foreign_transaction_fee: boolean;
  credit_score_minimum: number;
  is_business: boolean;
  key_perks: string[];
  pairs_well_with: string[];
  apply_url: string;
  active: boolean;
}

const CARDS: CreditCardSeed[] = [
  // ── CHASE ──────────────────────────────────────────────────────────────────
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    network: "visa",
    annual_fee: 95,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.25,
    earn_rates: { dining: 3, travel: 2, groceries: 3, streaming: 3, transit: 2, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "60,000 bonus points after $4,000 spend (~$750 toward travel via Chase portal)",
      "$50 annual hotel credit through Chase Travel",
      "10% anniversary points bonus on all purchases",
      "Primary rental car insurance + trip delay/cancellation protection",
    ],
    pairs_well_with: ["chase-freedom-unlimited", "chase-freedom-flex"],
    apply_url: "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred",
    active: true,
  },
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    network: "visa",
    annual_fee: 550,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 3, travel: 10, groceries: 1, streaming: 1, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$300 annual travel credit (automatically applies to travel purchases)",
      "Priority Pass lounge access for you + 2 guests at 1,400+ airport lounges",
      "Global Entry / TSA PreCheck credit ($120 every 4 years)",
      "Points worth 1.5¢ each through Chase portal; 1:1 transfer to United, Hyatt, BA, etc.",
    ],
    pairs_well_with: ["chase-freedom-unlimited", "chase-freedom-flex"],
    apply_url: "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve",
    active: true,
  },
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    network: "visa",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1.5 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "1.5% cash back (or 1.5x UR) on everything — best flat-rate earner with no fee",
      "3% on dining and drugstores, 5% on Chase Travel bookings",
      "Points transfer to Sapphire at 1:1 to unlock premium redemptions",
      "Cell phone protection up to $800 when you pay your phone bill with the card",
    ],
    pairs_well_with: ["chase-sapphire-preferred", "chase-sapphire-reserve", "chase-freedom-flex"],
    apply_url: "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
    active: true,
  },
  {
    id: "chase-freedom-flex",
    name: "Chase Freedom Flex",
    issuer: "Chase",
    network: "mastercard",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 5, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% on rotating quarterly categories (gas, groceries, Amazon, etc.) up to $1,500/quarter",
      "3% on dining and drugstores, 5% on Chase Travel",
      "No annual fee — stack with Sapphire Preferred/Reserve to maximize UR value",
      "Cell phone protection + purchase protection included",
    ],
    pairs_well_with: ["chase-sapphire-preferred", "chase-sapphire-reserve", "chase-freedom-unlimited"],
    apply_url: "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex",
    active: true,
  },
  {
    id: "chase-ink-business-preferred",
    name: "Ink Business Preferred",
    issuer: "Chase",
    network: "visa",
    annual_fee: 95,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.25,
    earn_rates: { dining: 1, travel: 3, groceries: 1, streaming: 3, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 1000,
    sign_up_bonus_spend: 8000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "100,000 bonus UR points after $8,000 spend — worth $1,250 via Chase Travel",
      "3x on travel, shipping, internet/cable/phone services, and advertising (up to $150k/yr)",
      "Cell phone protection up to $1,000 per claim for employee phones",
      "No foreign transaction fees; primary car rental coverage",
    ],
    pairs_well_with: ["chase-ink-business-cash", "chase-ink-business-unlimited"],
    apply_url: "https://creditcards.chase.com/business-credit-cards/ink/preferred",
    active: true,
  },
  {
    id: "chase-ink-business-cash",
    name: "Ink Business Cash",
    issuer: "Chase",
    network: "visa",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 1, groceries: 1, streaming: 1, transit: 1, gas: 2, base: 1 },
    sign_up_bonus_value: 350,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: true,
    key_perks: [
      "5% on office supply stores and internet/cable/phone (up to $25k/year)",
      "2% at gas stations and restaurants (up to $25k/year)",
      "No annual fee — stack with Ink Preferred to transfer cash back as UR points",
      "Employee cards at no additional cost",
    ],
    pairs_well_with: ["chase-ink-business-preferred", "chase-ink-business-unlimited"],
    apply_url: "https://creditcards.chase.com/business-credit-cards/ink/cash",
    active: true,
  },
  {
    id: "chase-ink-business-unlimited",
    name: "Ink Business Unlimited",
    issuer: "Chase",
    network: "visa",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1.5 },
    sign_up_bonus_value: 350,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: true,
    key_perks: [
      "1.5% cash back on every purchase — simple flat rate, no category tracking",
      "No annual fee — convert to UR by pairing with Ink Preferred or Sapphire",
      "0% intro APR for 12 months on purchases",
      "Free employee cards with spending limits",
    ],
    pairs_well_with: ["chase-ink-business-preferred", "chase-ink-business-cash"],
    apply_url: "https://creditcards.chase.com/business-credit-cards/ink/unlimited",
    active: true,
  },

  // ── AMEX ───────────────────────────────────────────────────────────────────
  {
    id: "amex-gold",
    name: "American Express Gold Card",
    issuer: "American Express",
    network: "amex",
    annual_fee: 250,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 4, travel: 3, groceries: 4, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 1000,
    sign_up_bonus_spend: 6000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "4x on restaurants worldwide and U.S. supermarkets (up to $25k/yr at supermarkets)",
      "$120 dining credit ($10/mo) at Grubhub, Seamless, The Cheesecake Factory, and more",
      "$120 Uber Cash annually ($10/mo) for Uber Eats or Uber rides in the U.S.",
      "MR points transfer to Delta, United, Emirates, Hilton, Marriott, and 15+ more",
    ],
    pairs_well_with: ["amex-platinum", "amex-blue-cash-preferred"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    active: true,
  },
  {
    id: "amex-platinum",
    name: "American Express Platinum Card",
    issuer: "American Express",
    network: "amex",
    annual_fee: 695,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 1, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 1500,
    sign_up_bonus_spend: 8000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 750,
    is_business: false,
    key_perks: [
      "5x on flights booked direct or through Amex Travel; 5x on prepaid hotels via Amex Travel",
      "$200 airline fee credit + $200 hotel credit + $100 Saks credit annually",
      "Centurion Lounge + Priority Pass + Delta Sky Club access (when flying Delta)",
      "Global Entry/TSA PreCheck credit; $189 CLEAR credit; Marriott + Hilton Gold status",
    ],
    pairs_well_with: ["amex-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/platinum-card/",
    active: true,
  },
  {
    id: "amex-blue-cash-preferred",
    name: "Blue Cash Preferred Card",
    issuer: "American Express",
    network: "amex",
    annual_fee: 95,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 6, streaming: 6, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 300,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "6% cash back at U.S. supermarkets (up to $6,000/yr), then 1%",
      "6% on select U.S. streaming (Netflix, Disney+, Hulu, etc.)",
      "3% on transit and U.S. gas stations",
      "$84 Disney Bundle credit annually ($7/mo), offsetting most of the annual fee",
    ],
    pairs_well_with: ["amex-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    active: true,
  },
  {
    id: "amex-blue-cash-everyday",
    name: "Blue Cash Everyday Card",
    issuer: "American Express",
    network: "amex",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 3, streaming: 3, transit: 1, gas: 2, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 2000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% at U.S. supermarkets (up to $6,000/yr) and U.S. online retail",
      "2% at U.S. gas stations",
      "No annual fee — great starter card for grocery rewards",
      "$84 Disney Bundle credit annually ($7/mo) for eligible streaming subscriptions",
    ],
    pairs_well_with: ["amex-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/",
    active: true,
  },
  {
    id: "amex-business-gold",
    name: "American Express Business Gold",
    issuer: "American Express",
    network: "amex",
    annual_fee: 295,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 4, travel: 4, groceries: 1, streaming: 1, transit: 1, gas: 4, base: 1 },
    sign_up_bonus_value: 1000,
    sign_up_bonus_spend: 10000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "4x on your top 2 eligible spend categories each billing cycle (up to $150k/yr)",
      "Categories include airfare, advertising, gas stations, restaurants, transit, and more",
      "$240 flexible business credit ($20/mo) for select software/shipping/advertising",
      "No preset spending limit; points transfer to 20+ airline and hotel partners",
    ],
    pairs_well_with: ["amex-business-platinum"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-business-gold-card/",
    active: true,
  },
  {
    id: "amex-business-platinum",
    name: "American Express Business Platinum",
    issuer: "American Express",
    network: "amex",
    annual_fee: 695,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 1, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 2000,
    sign_up_bonus_spend: 20000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: true,
    key_perks: [
      "5x on flights and prepaid hotels through Amex Travel; 1.5x on purchases over $5k",
      "$400 Dell credit + $360 Indeed credit + $150 Adobe credit annually",
      "Centurion Lounge + Priority Pass + Delta Sky Club access",
      "35% Pay with Points rebate on first-class/business-class flights",
    ],
    pairs_well_with: ["amex-business-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-business-platinum-card/",
    active: true,
  },
  {
    id: "amex-delta-gold",
    name: "Delta SkyMiles Gold American Express",
    issuer: "American Express",
    network: "amex",
    annual_fee: 150,
    rewards_program: "miles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 480,
    sign_up_bonus_spend: 2000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "First checked bag free on Delta flights for you and up to 8 companions",
      "2x miles on Delta purchases, restaurants, and U.S. supermarkets",
      "$200 Delta flight credit after $10k spend in a calendar year",
      "20% discount on in-flight purchases (food, beverages, audio headsets)",
    ],
    pairs_well_with: ["amex-delta-platinum"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-gold-american-express-card/",
    active: true,
  },
  {
    id: "amex-delta-platinum",
    name: "Delta SkyMiles Platinum American Express",
    issuer: "American Express",
    network: "amex",
    annual_fee: 350,
    rewards_program: "miles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 2, travel: 3, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Companion Certificate for a domestic round-trip ticket each card anniversary year",
      "3x miles on Delta purchases; 2x on restaurants and U.S. supermarkets",
      "Delta Medallion Qualification Miles boost; first bag free",
      "$120 Resy credit + $150 prepaid hotel credit through Delta Stays annually",
    ],
    pairs_well_with: ["amex-delta-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-platinum-american-express-card/",
    active: true,
  },

  // ── CAPITAL ONE ────────────────────────────────────────────────────────────
  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X",
    issuer: "Capital One",
    network: "visa",
    annual_fee: 395,
    rewards_program: "capital_one_miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 10, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$300 annual travel credit for bookings through Capital One Travel",
      "10,000 anniversary bonus miles each year (~$100 in travel value)",
      "Priority Pass + Capital One Lounge access for you and 2 guests",
      "2x miles on every purchase; 10x on hotels and rental cars via Capital One Travel",
    ],
    pairs_well_with: ["capital-one-venture"],
    apply_url: "https://capitalone.com/credit-cards/venture-x/",
    active: true,
  },
  {
    id: "capital-one-venture",
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    network: "visa",
    annual_fee: 95,
    rewards_program: "capital_one_miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 5, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "2x miles on every purchase — simple flat rate for travel-focused spenders",
      "5x miles on hotels and rental cars booked through Capital One Travel",
      "Global Entry / TSA PreCheck credit ($120 every 4 years)",
      "Transfer miles to 15+ airline and hotel partners including Air Canada, Turkish Airlines, Wyndham",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/venture/",
    active: true,
  },
  {
    id: "capital-one-quicksilver",
    name: "Capital One Quicksilver Cash Rewards",
    issuer: "Capital One",
    network: "visa",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.5, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 1.5 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "1.5% unlimited cash back on every purchase — no category tracking required",
      "No annual fee, no foreign transaction fees",
      "One-time $200 cash bonus after $500 spend in first 3 months",
      "0% intro APR for 15 months on purchases and balance transfers",
    ],
    pairs_well_with: ["capital-one-venture"],
    apply_url: "https://capitalone.com/credit-cards/quicksilver/",
    active: true,
  },
  {
    id: "capital-one-savorone",
    name: "Capital One SavorOne Cash Rewards",
    issuer: "Capital One",
    network: "mastercard",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 1, groceries: 3, streaming: 3, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% on dining, entertainment, grocery stores, and popular streaming services",
      "No annual fee, no foreign transaction fees",
      "8% back on Capital One Entertainment tickets and experiences",
      "0% intro APR for 15 months on purchases and balance transfers",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/savorone/",
    active: true,
  },
  {
    id: "capital-one-savor",
    name: "Capital One Savor Cash Rewards",
    issuer: "Capital One",
    network: "mastercard",
    annual_fee: 95,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 4, travel: 1, groceries: 4, streaming: 4, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 500,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "4% on dining, entertainment, and popular streaming services",
      "4% at grocery stores (excluding superstores like Walmart/Target)",
      "8% on Capital One Entertainment; no foreign transaction fees",
      "Travel accident insurance and extended warranty protection",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/savor/",
    active: true,
  },
  {
    id: "capital-one-spark-cash-plus",
    name: "Capital One Spark Cash Plus",
    issuer: "Capital One",
    network: "mastercard",
    annual_fee: 150,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 5, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 1200,
    sign_up_bonus_spend: 30000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "2% cash back on every purchase — unlimited, no category caps",
      "$150 annual fee refunded if you spend $150k+ in a calendar year",
      "5% on hotels and rental cars via Capital One Travel",
      "No preset spending limit; free employee cards",
    ],
    pairs_well_with: [],
    apply_url: "https://capitalone.com/small-business/credit-cards/spark-cash-plus/",
    active: true,
  },

  // ── CITI ───────────────────────────────────────────────────────────────────
  {
    id: "citi-double-cash",
    name: "Citi Double Cash Card",
    issuer: "Citi",
    network: "mastercard",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1500,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "2% cash back on everything — 1% when you buy, 1% when you pay",
      "Earn ThankYou Points (convertible to cash or transfers with Citi Premier)",
      "No annual fee; 0% intro APR on balance transfers for 18 months",
      "Simple, best-in-class flat rate — ideal as an everyday catch-all card",
    ],
    pairs_well_with: ["citi-premier"],
    apply_url: "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
    active: true,
  },
  {
    id: "citi-premier",
    name: "Citi Premier Card",
    issuer: "Citi",
    network: "mastercard",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.8,
    earn_rates: { dining: 3, travel: 3, groceries: 3, streaming: 1, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "3x ThankYou Points on restaurants, supermarkets, gas stations, air travel, and hotels",
      "$100 annual hotel savings benefit on $500+ single hotel booking via thankyou.com",
      "Transfer points to 18 airline partners including JetBlue, Singapore Airlines, Turkish Airlines",
      "No foreign transaction fees",
    ],
    pairs_well_with: ["citi-double-cash"],
    apply_url: "https://www.citi.com/credit-cards/citi-premier-credit-card",
    active: true,
  },
  {
    id: "citi-custom-cash",
    name: "Citi Custom Cash Card",
    issuer: "Citi",
    network: "mastercard",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 5, travel: 1, groceries: 5, streaming: 5, transit: 5, gas: 5, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1500,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% cash back on your top eligible spend category each billing cycle (up to $500/mo)",
      "Eligible categories: restaurants, gas, groceries, home improvement, live entertainment, travel, and more",
      "1% on all other purchases; no annual fee",
      "Automatic — no category activation needed, just spend and earn",
    ],
    pairs_well_with: ["citi-double-cash", "citi-premier"],
    apply_url: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    active: true,
  },

  // ── DISCOVER ───────────────────────────────────────────────────────────────
  {
    id: "discover-it-cash-back",
    name: "Discover it Cash Back",
    issuer: "Discover",
    network: "discover",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 5, streaming: 1, transit: 1, gas: 5, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 580,
    is_business: false,
    key_perks: [
      "5% on rotating quarterly categories (gas, groceries, Amazon, restaurants, etc.) up to $1,500/quarter",
      "Cashback Match: Discover automatically matches ALL cash back earned in first year",
      "No annual fee; FICO score on every statement",
      "No foreign transaction fees; excellent for international travel",
    ],
    pairs_well_with: [],
    apply_url: "https://www.discover.com/credit-cards/cash-back/it-card.html",
    active: true,
  },
  {
    id: "discover-it-miles",
    name: "Discover it Miles",
    issuer: "Discover",
    network: "discover",
    annual_fee: 0,
    rewards_program: "miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.5, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 1.5 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 580,
    is_business: false,
    key_perks: [
      "1.5x miles on every purchase — Discover matches all miles at end of first year",
      "Miles can be redeemed for travel statement credits or cash at 1¢/mile",
      "No annual fee, no foreign transaction fees",
      "FICO score tracking and free Social Security number alerts",
    ],
    pairs_well_with: [],
    apply_url: "https://www.discover.com/credit-cards/travel/it-miles-card.html",
    active: true,
  },

  // ── WELLS FARGO ────────────────────────────────────────────────────────────
  {
    id: "wells-fargo-active-cash",
    name: "Wells Fargo Active Cash Card",
    issuer: "Wells Fargo",
    network: "visa",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "2% unlimited cash rewards on every purchase — no categories, no limits",
      "No annual fee; 0% intro APR for 15 months on purchases and balance transfers",
      "$200 cash rewards bonus after $500 spend in first 3 months",
      "Cell phone protection up to $600 per claim when you pay monthly bill",
    ],
    pairs_well_with: [],
    apply_url: "https://www.wellsfargo.com/credit-cards/active-cash/",
    active: true,
  },
  {
    id: "wells-fargo-autograph",
    name: "Wells Fargo Autograph Card",
    issuer: "Wells Fargo",
    network: "visa",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 3, groceries: 1, streaming: 3, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3x points on restaurants, travel, gas, transit, streaming, and phone plans",
      "No annual fee, no foreign transaction fees",
      "20,000 bonus points ($200) after $1,000 spend in first 3 months",
      "0% intro APR for 12 months on purchases",
    ],
    pairs_well_with: ["wells-fargo-active-cash"],
    apply_url: "https://www.wellsfargo.com/credit-cards/autograph/",
    active: true,
  },

  // ── US BANK ────────────────────────────────────────────────────────────────
  {
    id: "us-bank-cash-plus",
    name: "U.S. Bank Cash+ Visa Signature",
    issuer: "U.S. Bank",
    network: "visa",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 1, groceries: 2, streaming: 5, transit: 2, gas: 5, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 120,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% on your first two chosen categories each quarter (including streaming, home utilities, gyms, fast food)",
      "2% on your chosen everyday category (gas, grocery, restaurant)",
      "1% on everything else; no annual fee",
      "Flexible category selection each quarter — customize to your spending patterns",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/cash-plus-visa-credit-card.html",
    active: true,
  },
  {
    id: "us-bank-altitude-reserve",
    name: "U.S. Bank Altitude Reserve Visa Infinite",
    issuer: "U.S. Bank",
    network: "visa",
    annual_fee: 400,
    rewards_program: "points",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 1, travel: 5, groceries: 1, streaming: 1, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$325 annual travel and dining credit — applies broadly to restaurants and transit",
      "3x points on mobile wallet purchases (Apple Pay, Google Pay) at any merchant",
      "5x on prepaid hotels and car rentals via Altitude Rewards Center",
      "Priority Pass lounge access; Global Entry/TSA PreCheck credit",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/altitude-reserve-visa-infinite-credit-card.html",
    active: true,
  },
  {
    id: "us-bank-altitude-go",
    name: "U.S. Bank Altitude Go Visa Signature",
    issuer: "U.S. Bank",
    network: "visa",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 4, travel: 2, groceries: 2, streaming: 4, transit: 2, gas: 2, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "4x points on dining and takeout, 4x on streaming services",
      "$15 annual streaming credit after $75 annual streaming spend",
      "2x on groceries, gas, and EV charging; no annual fee",
      "No foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/altitude-go-visa-signature-credit-card.html",
    active: true,
  },

  // ── BANK OF AMERICA ────────────────────────────────────────────────────────
  {
    id: "bofa-customized-cash-rewards",
    name: "Bank of America Customized Cash Rewards",
    issuer: "Bank of America",
    network: "visa",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 3, transit: 2, gas: 3, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% in your choice category (gas, online shopping, dining, travel, home improvement, or drug stores)",
      "2% at grocery stores and wholesale clubs (up to $2,500/quarter in 2%+3% categories combined)",
      "Preferred Rewards members earn 25-75% more on every purchase",
      "No annual fee; $200 cash bonus after $1,000 spend in first 90 days",
    ],
    pairs_well_with: ["bofa-premium-rewards"],
    apply_url: "https://www.bankofamerica.com/credit-cards/products/customized-cash-rewards-credit-card/",
    active: true,
  },
  {
    id: "bofa-premium-rewards",
    name: "Bank of America Premium Rewards",
    issuer: "Bank of America",
    network: "visa",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 2, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "2x points on travel and dining; 1.5x on all other purchases",
      "$100 annual airline incidental credit + $100 Global Entry/TSA PreCheck credit",
      "Preferred Rewards Platinum: earn up to 3.5x on travel, 2.62x on dining",
      "No foreign transaction fees; travel insurance and purchase protection included",
    ],
    pairs_well_with: ["bofa-customized-cash-rewards"],
    apply_url: "https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/",
    active: true,
  },

  // ── OTHER ──────────────────────────────────────────────────────────────────
  {
    id: "bilt-rewards",
    name: "Bilt Mastercard",
    issuer: "Wells Fargo",
    network: "mastercard",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 3, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Earn points on rent with no transaction fees — unique in the credit card market",
      "1x on rent (up to 50k/yr), 3x on dining, 2x on travel",
      "Transfer points to American Airlines, United, Alaska, Hyatt, Marriott, and more",
      "Lyft Pink membership; DoorDash DashPass included",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://www.biltrewards.com/card",
    active: true,
  },
  {
    id: "apple-card",
    name: "Apple Card",
    issuer: "Goldman Sachs",
    network: "mastercard",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% Daily Cash at Apple, and select merchants (Uber, Lyft, Nike, T-Mobile, etc.)",
      "2% Daily Cash when using Apple Pay; 1% on physical card swipes",
      "Daily Cash deposited directly to Apple Cash — no waiting for statement credits",
      "No fees of any kind: no annual, foreign transaction, late, or over-limit fees",
    ],
    pairs_well_with: [],
    apply_url: "https://www.apple.com/apple-card/",
    active: true,
  },
  {
    id: "fidelity-rewards-visa",
    name: "Fidelity Rewards Visa Signature",
    issuer: "Elan Financial",
    network: "visa",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 150,
    sign_up_bonus_spend: 1500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Unlimited 2% cash back deposited directly into eligible Fidelity account",
      "No annual fee, no foreign transaction fees",
      "Great for investors — rewards automatically boost retirement or brokerage savings",
      "Cell phone protection; extended warranty included",
    ],
    pairs_well_with: [],
    apply_url: "https://www.fidelity.com/cash-management/visa-signature-card",
    active: true,
  },
  {
    id: "united-explorer",
    name: "United Explorer Card",
    issuer: "Chase",
    network: "visa",
    annual_fee: 95,
    rewards_program: "miles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Free first checked bag for you and a companion on every United flight",
      "2x miles on United purchases, restaurants, and hotels",
      "Two United Club one-time passes per year (value $119 each)",
      "25% back on United inflight purchases; no foreign transaction fees",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/united/explorer",
    active: true,
  },
  {
    id: "southwest-rapid-rewards-premier",
    name: "Southwest Rapid Rewards Premier",
    issuer: "Chase",
    network: "visa",
    annual_fee: 99,
    rewards_program: "points",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 2, travel: 3, groceries: 2, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3x points on Southwest purchases; 2x on hotels and car rentals through Southwest",
      "6,000 anniversary points every year (worth ~$90)",
      "Earn toward A-List status and Companion Pass (requires 135k points in a year)",
      "Two EarlyBird Check-In per year; no foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/southwest/premier",
    active: true,
  },
  {
    id: "marriott-bonvoy-boundless",
    name: "Marriott Bonvoy Boundless",
    issuer: "Chase",
    network: "visa",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 0.9,
    earn_rates: { dining: 2, travel: 6, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 450,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Free Night Award (worth up to 35,000 points) each card anniversary",
      "6x points at Marriott hotels; 2x on all other purchases",
      "Automatic Silver Elite status; spending $35k/year earns Gold Elite status",
      "No foreign transaction fees; 15 Elite Night Credits per year toward status",
    ],
    pairs_well_with: [],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/boundless",
    active: true,
  },
  {
    id: "world-of-hyatt",
    name: "World of Hyatt Credit Card",
    issuer: "Chase",
    network: "visa",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.7,
    earn_rates: { dining: 2, travel: 4, groceries: 1, streaming: 1, transit: 2, gas: 1, base: 1 },
    sign_up_bonus_value: 850,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Free Night Award at Category 1-4 hotel each anniversary year (value up to $150)",
      "4x points at Hyatt hotels and spas; 2x on dining, airlines, gyms, and transit",
      "Automatic Discoverist status; 5 qualifying night credits per year toward status",
      "Hyatt points are among the highest-value hotel currencies at ~1.7¢/point",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/world-of-hyatt",
    active: true,
  },
  {
    id: "ihg-one-rewards-premier",
    name: "IHG One Rewards Premier",
    issuer: "Chase",
    network: "mastercard",
    annual_fee: 99,
    rewards_program: "points",
    rewards_value_cpp: 0.5,
    earn_rates: { dining: 3, travel: 5, groceries: 3, streaming: 1, transit: 1, gas: 1, base: 3 },
    sign_up_bonus_value: 450,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Free Night Reward (worth up to 40,000 points) each card anniversary",
      "26x points at IHG Hotels when you use the card + Rewards Club + Platinum Elite",
      "Automatic Platinum Elite status; fourth night free on IHG award bookings",
      "Global Entry/TSA PreCheck credit; no foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/ihg/premier",
    active: true,
  },
];

async function seed() {
  const db = getSupabaseAdmin();
  console.log(`Seeding ${CARDS.length} credit cards...`);

  const { error } = await db
    .from("credit_cards")
    .upsert(CARDS, { onConflict: "id" });

  if (error) {
    console.error("Seed failed:", error.message);
    process.exit(1);
  }

  console.log(`Successfully seeded ${CARDS.length} cards.`);
}

seed();
