/**
 * Seed script for credit_cards table.
 * Run with: npx tsx lib/credit-cards-seed.ts
 */

import { getSupabaseAdmin } from "./supabase";

interface CreditCardSeed {
  id: string;
  name: string;
  issuer: string;
  network: string;
  country: "US" | "CA";
  annual_fee: number;
  rewards_program: string;
  rewards_value_cpp: number;
  earn_rates: Record<string, number>;
  sign_up_bonus_value: number;
  sign_up_bonus_spend: number;
  sign_up_bonus_days: number;
  foreign_transaction_fee: boolean;
  credit_score_minimum: number;
  is_business: boolean;
  key_perks: string[];
  pairs_well_with: string[];
  apply_url: string;
  active: boolean;
}

const CARDS: CreditCardSeed[] = [
  // ── CHASE ──────────────────────────────────────────────────────────────────
  {
    id: "chase-sapphire-preferred",
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.25,
    earn_rates: { dining: 3, travel: 2, groceries: 3, streaming: 3, transit: 2, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "60,000 bonus points after $4,000 spend (~$750 toward travel via Chase portal)",
      "$50 annual hotel credit through Chase Travel",
      "10% anniversary points bonus on all purchases",
      "Primary rental car insurance + trip delay/cancellation protection",
    ],
    pairs_well_with: ["chase-freedom-unlimited", "chase-freedom-flex"],
    apply_url: "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred",
    active: true,
  },
  {
    id: "chase-sapphire-reserve",
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 550,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 3, travel: 10, groceries: 1, streaming: 1, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$300 annual travel credit (automatically applies to travel purchases)",
      "Priority Pass lounge access for you + 2 guests at 1,400+ airport lounges",
      "Global Entry / TSA PreCheck credit ($120 every 4 years)",
      "Points worth 1.5¢ each through Chase portal; 1:1 transfer to United, Hyatt, BA, etc.",
    ],
    pairs_well_with: ["chase-freedom-unlimited", "chase-freedom-flex"],
    apply_url: "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve",
    active: true,
  },
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1.5 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "1.5% cash back (or 1.5x UR) on everything — best flat-rate earner with no fee",
      "3% on dining and drugstores, 5% on Chase Travel bookings",
      "Points transfer to Sapphire at 1:1 to unlock premium redemptions",
      "Cell phone protection up to $800 when you pay your phone bill with the card",
    ],
    pairs_well_with: ["chase-sapphire-preferred", "chase-sapphire-reserve", "chase-freedom-flex"],
    apply_url: "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
    active: true,
  },
  {
    id: "chase-freedom-flex",
    name: "Chase Freedom Flex",
    issuer: "Chase",
    network: "mastercard",
    country: "US",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 5, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% on rotating quarterly categories (gas, groceries, Amazon, etc.) up to $1,500/quarter",
      "3% on dining and drugstores, 5% on Chase Travel",
      "No annual fee — stack with Sapphire Preferred/Reserve to maximize UR value",
      "Cell phone protection + purchase protection included",
    ],
    pairs_well_with: ["chase-sapphire-preferred", "chase-sapphire-reserve", "chase-freedom-unlimited"],
    apply_url: "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex",
    active: true,
  },
  {
    id: "chase-ink-business-preferred",
    name: "Ink Business Preferred",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.25,
    earn_rates: { dining: 1, travel: 3, groceries: 1, streaming: 3, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 1000,
    sign_up_bonus_spend: 8000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "100,000 bonus UR points after $8,000 spend — worth $1,250 via Chase Travel",
      "3x on travel, shipping, internet/cable/phone services, and advertising (up to $150k/yr)",
      "Cell phone protection up to $1,000 per claim for employee phones",
      "No foreign transaction fees; primary car rental coverage",
    ],
    pairs_well_with: ["chase-ink-business-cash", "chase-ink-business-unlimited"],
    apply_url: "https://creditcards.chase.com/business-credit-cards/ink/preferred",
    active: true,
  },
  {
    id: "chase-ink-business-cash",
    name: "Ink Business Cash",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 1, groceries: 1, streaming: 1, transit: 1, gas: 2, base: 1 },
    sign_up_bonus_value: 350,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: true,
    key_perks: [
      "5% on office supply stores and internet/cable/phone (up to $25k/year)",
      "2% at gas stations and restaurants (up to $25k/year)",
      "No annual fee — stack with Ink Preferred to transfer cash back as UR points",
      "Employee cards at no additional cost",
    ],
    pairs_well_with: ["chase-ink-business-preferred", "chase-ink-business-unlimited"],
    apply_url: "https://creditcards.chase.com/business-credit-cards/ink/cash",
    active: true,
  },
  {
    id: "chase-ink-business-unlimited",
    name: "Ink Business Unlimited",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "chase_ur",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1.5 },
    sign_up_bonus_value: 350,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: true,
    key_perks: [
      "1.5% cash back on every purchase — simple flat rate, no category tracking",
      "No annual fee — convert to UR by pairing with Ink Preferred or Sapphire",
      "0% intro APR for 12 months on purchases",
      "Free employee cards with spending limits",
    ],
    pairs_well_with: ["chase-ink-business-preferred", "chase-ink-business-cash"],
    apply_url: "https://creditcards.chase.com/business-credit-cards/ink/unlimited",
    active: true,
  },

  // ── AMEX ───────────────────────────────────────────────────────────────────
  {
    id: "amex-green",
    name: "American Express Green Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 150,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 3, travel: 3, groceries: 1, streaming: 1, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3x Membership Rewards on travel, transit, and restaurants worldwide",
      "$189 CLEAR Plus credit annually (airport security fast lane)",
      "$100 LoungeBuddy credit for single-visit lounge access",
      "Transfers to 20+ airline and hotel partners; no foreign transaction fees",
    ],
    pairs_well_with: ["amex-gold", "amex-platinum"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/green-card/",
    active: true,
  },
  {
    id: "amex-gold",
    name: "American Express Gold Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 250,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 4, travel: 3, groceries: 4, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 1000,
    sign_up_bonus_spend: 6000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "4x on restaurants worldwide and U.S. supermarkets (up to $25k/yr at supermarkets)",
      "$120 dining credit ($10/mo) at Grubhub, Seamless, The Cheesecake Factory, and more",
      "$120 Uber Cash annually ($10/mo) for Uber Eats or Uber rides in the U.S.",
      "MR points transfer to Delta, United, Emirates, Hilton, Marriott, and 15+ more",
    ],
    pairs_well_with: ["amex-platinum", "amex-blue-cash-preferred"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/gold-card/",
    active: true,
  },
  {
    id: "amex-platinum",
    name: "American Express Platinum Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 695,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 1, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 1500,
    sign_up_bonus_spend: 8000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 750,
    is_business: false,
    key_perks: [
      "5x on flights booked direct or through Amex Travel; 5x on prepaid hotels via Amex Travel",
      "$200 airline fee credit + $200 hotel credit + $100 Saks credit annually",
      "Centurion Lounge + Priority Pass + Delta Sky Club access (when flying Delta)",
      "Global Entry/TSA PreCheck credit; $189 CLEAR credit; Marriott + Hilton Gold status",
    ],
    pairs_well_with: ["amex-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/platinum-card/",
    active: true,
  },
  {
    id: "amex-blue-cash-preferred",
    name: "Blue Cash Preferred Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 95,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 6, streaming: 6, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 300,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "6% cash back at U.S. supermarkets (up to $6,000/yr), then 1%",
      "6% on select U.S. streaming (Netflix, Disney+, Hulu, etc.)",
      "3% on transit and U.S. gas stations",
      "$84 Disney Bundle credit annually ($7/mo), offsetting most of the annual fee",
    ],
    pairs_well_with: ["amex-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
    active: true,
  },
  {
    id: "amex-blue-cash-everyday",
    name: "Blue Cash Everyday Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 3, streaming: 3, transit: 1, gas: 2, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 2000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% at U.S. supermarkets (up to $6,000/yr) and U.S. online retail",
      "2% at U.S. gas stations",
      "No annual fee — great starter card for grocery rewards",
      "$84 Disney Bundle credit annually ($7/mo) for eligible streaming subscriptions",
    ],
    pairs_well_with: ["amex-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/",
    active: true,
  },
  {
    id: "amex-business-gold",
    name: "American Express Business Gold",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 295,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 4, travel: 4, groceries: 1, streaming: 1, transit: 1, gas: 4, base: 1 },
    sign_up_bonus_value: 1000,
    sign_up_bonus_spend: 10000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "4x on your top 2 eligible spend categories each billing cycle (up to $150k/yr)",
      "Categories include airfare, advertising, gas stations, restaurants, transit, and more",
      "$240 flexible business credit ($20/mo) for select software/shipping/advertising",
      "No preset spending limit; points transfer to 20+ airline and hotel partners",
    ],
    pairs_well_with: ["amex-business-platinum"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-business-gold-card/",
    active: true,
  },
  {
    id: "amex-business-platinum",
    name: "American Express Business Platinum",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 695,
    rewards_program: "amex_mr",
    rewards_value_cpp: 2.0,
    earn_rates: { dining: 1, travel: 5, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 2000,
    sign_up_bonus_spend: 20000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: true,
    key_perks: [
      "5x on flights and prepaid hotels through Amex Travel; 1.5x on purchases over $5k",
      "$400 Dell credit + $360 Indeed credit + $150 Adobe credit annually",
      "Centurion Lounge + Priority Pass + Delta Sky Club access",
      "35% Pay with Points rebate on first-class/business-class flights",
    ],
    pairs_well_with: ["amex-business-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/american-express-business-platinum-card/",
    active: true,
  },
  {
    id: "amex-delta-gold",
    name: "Delta SkyMiles Gold American Express",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 150,
    rewards_program: "miles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 480,
    sign_up_bonus_spend: 2000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "First checked bag free on Delta flights for you and up to 8 companions",
      "2x miles on Delta purchases, restaurants, and U.S. supermarkets",
      "$200 Delta flight credit after $10k spend in a calendar year",
      "20% discount on in-flight purchases (food, beverages, audio headsets)",
    ],
    pairs_well_with: ["amex-delta-platinum"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-gold-american-express-card/",
    active: true,
  },
  {
    id: "amex-delta-platinum",
    name: "Delta SkyMiles Platinum American Express",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 350,
    rewards_program: "miles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 2, travel: 3, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Companion Certificate for a domestic round-trip ticket each card anniversary year",
      "3x miles on Delta purchases; 2x on restaurants and U.S. supermarkets",
      "Delta Medallion Qualification Miles boost; first bag free",
      "$120 Resy credit + $150 prepaid hotel credit through Delta Stays annually",
    ],
    pairs_well_with: ["amex-delta-gold"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-platinum-american-express-card/",
    active: true,
  },

  // ── CAPITAL ONE ────────────────────────────────────────────────────────────
  {
    id: "capital-one-venture-x",
    name: "Capital One Venture X",
    issuer: "Capital One",
    network: "visa",
    country: "US",
    annual_fee: 395,
    rewards_program: "capital_one_miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 10, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$300 annual travel credit for bookings through Capital One Travel",
      "10,000 anniversary bonus miles each year (~$100 in travel value)",
      "Priority Pass + Capital One Lounge access for you and 2 guests",
      "2x miles on every purchase; 10x on hotels and rental cars via Capital One Travel",
    ],
    pairs_well_with: ["capital-one-venture"],
    apply_url: "https://capitalone.com/credit-cards/venture-x/",
    active: true,
  },
  {
    id: "capital-one-venture",
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "capital_one_miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 5, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "2x miles on every purchase — simple flat rate for travel-focused spenders",
      "5x miles on hotels and rental cars booked through Capital One Travel",
      "Global Entry / TSA PreCheck credit ($120 every 4 years)",
      "Transfer miles to 15+ airline and hotel partners including Air Canada, Turkish Airlines, Wyndham",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/venture/",
    active: true,
  },
  {
    id: "capital-one-quicksilver",
    name: "Capital One Quicksilver Cash Rewards",
    issuer: "Capital One",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.5, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 1.5 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "1.5% unlimited cash back on every purchase — no category tracking required",
      "No annual fee, no foreign transaction fees",
      "One-time $200 cash bonus after $500 spend in first 3 months",
      "0% intro APR for 15 months on purchases and balance transfers",
    ],
    pairs_well_with: ["capital-one-venture"],
    apply_url: "https://capitalone.com/credit-cards/quicksilver/",
    active: true,
  },
  {
    id: "capital-one-savorone",
    name: "Capital One SavorOne Cash Rewards",
    issuer: "Capital One",
    network: "mastercard",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 1, groceries: 3, streaming: 3, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% on dining, entertainment, grocery stores, and popular streaming services",
      "No annual fee, no foreign transaction fees",
      "8% back on Capital One Entertainment tickets and experiences",
      "0% intro APR for 15 months on purchases and balance transfers",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/savorone/",
    active: true,
  },
  {
    id: "capital-one-savor",
    name: "Capital One Savor Cash Rewards",
    issuer: "Capital One",
    network: "mastercard",
    country: "US",
    annual_fee: 95,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 4, travel: 1, groceries: 4, streaming: 4, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 500,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "4% on dining, entertainment, and popular streaming services",
      "4% at grocery stores (excluding superstores like Walmart/Target)",
      "8% on Capital One Entertainment; no foreign transaction fees",
      "Travel accident insurance and extended warranty protection",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/savor/",
    active: true,
  },
  {
    id: "capital-one-spark-cash-plus",
    name: "Capital One Spark Cash Plus",
    issuer: "Capital One",
    network: "mastercard",
    country: "US",
    annual_fee: 150,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 5, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 1200,
    sign_up_bonus_spend: 30000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "2% cash back on every purchase — unlimited, no category caps",
      "$150 annual fee refunded if you spend $150k+ in a calendar year",
      "5% on hotels and rental cars via Capital One Travel",
      "No preset spending limit; free employee cards",
    ],
    pairs_well_with: [],
    apply_url: "https://capitalone.com/small-business/credit-cards/spark-cash-plus/",
    active: true,
  },

  // ── CITI ───────────────────────────────────────────────────────────────────
  {
    id: "citi-double-cash",
    name: "Citi Double Cash Card",
    issuer: "Citi",
    network: "mastercard",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1500,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "2% cash back on everything — 1% when you buy, 1% when you pay",
      "Earn ThankYou Points (convertible to cash or transfers with Citi Premier)",
      "No annual fee; 0% intro APR on balance transfers for 18 months",
      "Simple, best-in-class flat rate — ideal as an everyday catch-all card",
    ],
    pairs_well_with: ["citi-premier"],
    apply_url: "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
    active: true,
  },
  {
    id: "citi-premier",
    name: "Citi Premier Card",
    issuer: "Citi",
    network: "mastercard",
    country: "US",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.8,
    earn_rates: { dining: 3, travel: 3, groceries: 3, streaming: 1, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "3x ThankYou Points on restaurants, supermarkets, gas stations, air travel, and hotels",
      "$100 annual hotel savings benefit on $500+ single hotel booking via thankyou.com",
      "Transfer points to 18 airline partners including JetBlue, Singapore Airlines, Turkish Airlines",
      "No foreign transaction fees",
    ],
    pairs_well_with: ["citi-double-cash"],
    apply_url: "https://www.citi.com/credit-cards/citi-premier-credit-card",
    active: true,
  },
  {
    id: "citi-custom-cash",
    name: "Citi Custom Cash Card",
    issuer: "Citi",
    network: "mastercard",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 5, travel: 1, groceries: 5, streaming: 5, transit: 5, gas: 5, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1500,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% cash back on your top eligible spend category each billing cycle (up to $500/mo)",
      "Eligible categories: restaurants, gas, groceries, home improvement, live entertainment, travel, and more",
      "1% on all other purchases; no annual fee",
      "Automatic — no category activation needed, just spend and earn",
    ],
    pairs_well_with: ["citi-double-cash", "citi-premier"],
    apply_url: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card",
    active: true,
  },

  // ── DISCOVER ───────────────────────────────────────────────────────────────
  {
    id: "discover-it-cash-back",
    name: "Discover it Cash Back",
    issuer: "Discover",
    network: "discover",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 5, streaming: 1, transit: 1, gas: 5, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 580,
    is_business: false,
    key_perks: [
      "5% on rotating quarterly categories (gas, groceries, Amazon, restaurants, etc.) up to $1,500/quarter",
      "Cashback Match: Discover automatically matches ALL cash back earned in first year",
      "No annual fee; FICO score on every statement",
      "No foreign transaction fees; excellent for international travel",
    ],
    pairs_well_with: [],
    apply_url: "https://www.discover.com/credit-cards/cash-back/it-card.html",
    active: true,
  },
  {
    id: "discover-it-miles",
    name: "Discover it Miles",
    issuer: "Discover",
    network: "discover",
    country: "US",
    annual_fee: 0,
    rewards_program: "miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.5, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 1.5 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 580,
    is_business: false,
    key_perks: [
      "1.5x miles on every purchase — Discover matches all miles at end of first year",
      "Miles can be redeemed for travel statement credits or cash at 1¢/mile",
      "No annual fee, no foreign transaction fees",
      "FICO score tracking and free Social Security number alerts",
    ],
    pairs_well_with: [],
    apply_url: "https://www.discover.com/credit-cards/travel/it-miles-card.html",
    active: true,
  },

  // ── WELLS FARGO ────────────────────────────────────────────────────────────
  {
    id: "wells-fargo-active-cash",
    name: "Wells Fargo Active Cash Card",
    issuer: "Wells Fargo",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "2% unlimited cash rewards on every purchase — no categories, no limits",
      "No annual fee; 0% intro APR for 15 months on purchases and balance transfers",
      "$200 cash rewards bonus after $500 spend in first 3 months",
      "Cell phone protection up to $600 per claim when you pay monthly bill",
    ],
    pairs_well_with: [],
    apply_url: "https://www.wellsfargo.com/credit-cards/active-cash/",
    active: true,
  },
  {
    id: "wells-fargo-autograph",
    name: "Wells Fargo Autograph Card",
    issuer: "Wells Fargo",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 3, groceries: 1, streaming: 3, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3x points on restaurants, travel, gas, transit, streaming, and phone plans",
      "No annual fee, no foreign transaction fees",
      "20,000 bonus points ($200) after $1,000 spend in first 3 months",
      "0% intro APR for 12 months on purchases",
    ],
    pairs_well_with: ["wells-fargo-active-cash"],
    apply_url: "https://www.wellsfargo.com/credit-cards/autograph/",
    active: true,
  },

  // ── US BANK ────────────────────────────────────────────────────────────────
  {
    id: "us-bank-cash-plus",
    name: "U.S. Bank Cash+ Visa Signature",
    issuer: "U.S. Bank",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 1, groceries: 2, streaming: 5, transit: 2, gas: 5, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 120,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% on your first two chosen categories each quarter (including streaming, home utilities, gyms, fast food)",
      "2% on your chosen everyday category (gas, grocery, restaurant)",
      "1% on everything else; no annual fee",
      "Flexible category selection each quarter — customize to your spending patterns",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/cash-plus-visa-credit-card.html",
    active: true,
  },
  {
    id: "us-bank-altitude-reserve",
    name: "U.S. Bank Altitude Reserve Visa Infinite",
    issuer: "U.S. Bank",
    network: "visa",
    country: "US",
    annual_fee: 400,
    rewards_program: "points",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 1, travel: 5, groceries: 1, streaming: 1, transit: 3, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 4500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$325 annual travel and dining credit — applies broadly to restaurants and transit",
      "3x points on mobile wallet purchases (Apple Pay, Google Pay) at any merchant",
      "5x on prepaid hotels and car rentals via Altitude Rewards Center",
      "Priority Pass lounge access; Global Entry/TSA PreCheck credit",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/altitude-reserve-visa-infinite-credit-card.html",
    active: true,
  },
  {
    id: "us-bank-altitude-go",
    name: "U.S. Bank Altitude Go Visa Signature",
    issuer: "U.S. Bank",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 4, travel: 2, groceries: 2, streaming: 4, transit: 2, gas: 2, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "4x points on dining and takeout, 4x on streaming services",
      "$15 annual streaming credit after $75 annual streaming spend",
      "2x on groceries, gas, and EV charging; no annual fee",
      "No foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/altitude-go-visa-signature-credit-card.html",
    active: true,
  },

  // ── BANK OF AMERICA ────────────────────────────────────────────────────────
  {
    id: "bofa-customized-cash-rewards",
    name: "Bank of America Customized Cash Rewards",
    issuer: "Bank of America",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 3, transit: 2, gas: 3, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% in your choice category (gas, online shopping, dining, travel, home improvement, or drug stores)",
      "2% at grocery stores and wholesale clubs (up to $2,500/quarter in 2%+3% categories combined)",
      "Preferred Rewards members earn 25-75% more on every purchase",
      "No annual fee; $200 cash bonus after $1,000 spend in first 90 days",
    ],
    pairs_well_with: ["bofa-premium-rewards"],
    apply_url: "https://www.bankofamerica.com/credit-cards/products/customized-cash-rewards-credit-card/",
    active: true,
  },
  {
    id: "bofa-premium-rewards",
    name: "Bank of America Premium Rewards",
    issuer: "Bank of America",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 2, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "2x points on travel and dining; 1.5x on all other purchases",
      "$100 annual airline incidental credit + $100 Global Entry/TSA PreCheck credit",
      "Preferred Rewards Platinum: earn up to 3.5x on travel, 2.62x on dining",
      "No foreign transaction fees; travel insurance and purchase protection included",
    ],
    pairs_well_with: ["bofa-customized-cash-rewards"],
    apply_url: "https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/",
    active: true,
  },

  // ── OTHER ──────────────────────────────────────────────────────────────────
  {
    id: "bilt-rewards",
    name: "Bilt Mastercard",
    issuer: "Wells Fargo",
    network: "mastercard",
    country: "US",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 3, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Earn points on rent with no transaction fees — unique in the credit card market",
      "1x on rent (up to 50k/yr), 3x on dining, 2x on travel",
      "Transfer points to American Airlines, United, Alaska, Hyatt, Marriott, and more",
      "Lyft Pink membership; DoorDash DashPass included",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://www.biltrewards.com/card",
    active: true,
  },
  {
    id: "apple-card",
    name: "Apple Card",
    issuer: "Goldman Sachs",
    network: "mastercard",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3% Daily Cash at Apple, and select merchants (Uber, Lyft, Nike, T-Mobile, etc.)",
      "2% Daily Cash when using Apple Pay; 1% on physical card swipes",
      "Daily Cash deposited directly to Apple Cash — no waiting for statement credits",
      "No fees of any kind: no annual, foreign transaction, late, or over-limit fees",
    ],
    pairs_well_with: [],
    apply_url: "https://www.apple.com/apple-card/",
    active: true,
  },
  {
    id: "fidelity-rewards-visa",
    name: "Fidelity Rewards Visa Signature",
    issuer: "Elan Financial",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 150,
    sign_up_bonus_spend: 1500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Unlimited 2% cash back deposited directly into eligible Fidelity account",
      "No annual fee, no foreign transaction fees",
      "Great for investors — rewards automatically boost retirement or brokerage savings",
      "Cell phone protection; extended warranty included",
    ],
    pairs_well_with: [],
    apply_url: "https://www.fidelity.com/cash-management/visa-signature-card",
    active: true,
  },
  {
    id: "united-explorer",
    name: "United Explorer Card",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "miles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Free first checked bag for you and a companion on every United flight",
      "2x miles on United purchases, restaurants, and hotels",
      "Two United Club one-time passes per year (value $119 each)",
      "25% back on United inflight purchases; no foreign transaction fees",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/united/explorer",
    active: true,
  },
  {
    id: "southwest-rapid-rewards-premier",
    name: "Southwest Rapid Rewards Premier",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 99,
    rewards_program: "points",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 2, travel: 3, groceries: 2, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "3x points on Southwest purchases; 2x on hotels and car rentals through Southwest",
      "6,000 anniversary points every year (worth ~$90)",
      "Earn toward A-List status and Companion Pass (requires 135k points in a year)",
      "Two EarlyBird Check-In per year; no foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/southwest/premier",
    active: true,
  },
  {
    id: "marriott-bonvoy-boundless",
    name: "Marriott Bonvoy Boundless",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 0.9,
    earn_rates: { dining: 2, travel: 6, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 450,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Free Night Award (worth up to 35,000 points) each card anniversary",
      "6x points at Marriott hotels; 2x on all other purchases",
      "Automatic Silver Elite status; spending $35k/year earns Gold Elite status",
      "No foreign transaction fees; 15 Elite Night Credits per year toward status",
    ],
    pairs_well_with: [],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/marriott-bonvoy/boundless",
    active: true,
  },
  {
    id: "world-of-hyatt",
    name: "World of Hyatt Credit Card",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.7,
    earn_rates: { dining: 2, travel: 4, groceries: 1, streaming: 1, transit: 2, gas: 1, base: 1 },
    sign_up_bonus_value: 850,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Free Night Award at Category 1-4 hotel each anniversary year (value up to $150)",
      "4x points at Hyatt hotels and spas; 2x on dining, airlines, gyms, and transit",
      "Automatic Discoverist status; 5 qualifying night credits per year toward status",
      "Hyatt points are among the highest-value hotel currencies at ~1.7¢/point",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/world-of-hyatt",
    active: true,
  },
  {
    id: "ihg-one-rewards-premier",
    name: "IHG One Rewards Premier",
    issuer: "Chase",
    network: "mastercard",
    country: "US",
    annual_fee: 99,
    rewards_program: "points",
    rewards_value_cpp: 0.5,
    earn_rates: { dining: 3, travel: 5, groceries: 3, streaming: 1, transit: 1, gas: 1, base: 3 },
    sign_up_bonus_value: 450,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "Free Night Reward (worth up to 40,000 points) each card anniversary",
      "26x points at IHG Hotels when you use the card + Rewards Club + Platinum Elite",
      "Automatic Platinum Elite status; fourth night free on IHG award bookings",
      "Global Entry/TSA PreCheck credit; no foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/ihg/premier",
    active: true,
  },

  // ── ADDITIONAL US CARDS ────────────────────────────────────────────────────
  {
    id: "amex-hilton-honors",
    name: "Hilton Honors American Express Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 0,
    rewards_program: "hilton_honors",
    rewards_value_cpp: 0.6,
    earn_rates: { dining: 5, travel: 3, groceries: 5, streaming: 1, transit: 1, gas: 3, base: 3 },
    sign_up_bonus_value: 168,
    sign_up_bonus_spend: 2000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "7x points at Hilton hotels; 5x at U.S. restaurants and supermarkets",
      "No annual fee; automatic Silver status in Hilton Honors",
      "Complimentary Hilton Honors membership with discounted member rates",
      "No foreign transaction fees",
    ],
    pairs_well_with: ["amex-hilton-honors-surpass"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/hilton-honors/",
    active: true,
  },
  {
    id: "amex-hilton-honors-surpass",
    name: "Hilton Honors American Express Surpass Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 150,
    rewards_program: "hilton_honors",
    rewards_value_cpp: 0.6,
    earn_rates: { dining: 12, travel: 6, groceries: 12, streaming: 3, transit: 3, gas: 6, base: 3 },
    sign_up_bonus_value: 180,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "12x points at Hilton hotels; 6x at U.S. restaurants, supermarkets, and gas stations",
      "Complimentary Gold status — room upgrades and breakfast at many properties",
      "Free Night Reward after $15,000 spend in a calendar year",
      "$50 annual Hilton resort statement credit; Priority Pass lounge access (10 visits/yr)",
    ],
    pairs_well_with: ["amex-hilton-honors"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/hilton-honors-surpass/",
    active: true,
  },
  {
    id: "amex-hilton-honors-aspire",
    name: "Hilton Honors American Express Aspire Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 550,
    rewards_program: "hilton_honors",
    rewards_value_cpp: 0.6,
    earn_rates: { dining: 14, travel: 7, groceries: 7, streaming: 3, transit: 3, gas: 3, base: 3 },
    sign_up_bonus_value: 300,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "Automatic Diamond status — best room upgrades and executive lounge access",
      "$200 Hilton resort credit + $200 flight credit each card year",
      "Free Night Reward each anniversary + another after $30k annual spend",
      "Priority Pass unlimited lounge access; no foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/hilton-honors-aspire/",
    active: true,
  },
  {
    id: "amex-marriott-bonvoy-brilliant",
    name: "Marriott Bonvoy Brilliant American Express Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 650,
    rewards_program: "marriott_bonvoy",
    rewards_value_cpp: 0.9,
    earn_rates: { dining: 6, travel: 6, groceries: 3, streaming: 3, transit: 3, gas: 3, base: 2 },
    sign_up_bonus_value: 900,
    sign_up_bonus_spend: 6000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "$300 annual dining credit at restaurants worldwide",
      "Free Night Award (up to 85,000 points) each card anniversary",
      "Automatic Platinum Elite status — suite upgrades, lounge access, bonus points",
      "Priority Pass unlimited lounge access; Global Entry/TSA PreCheck credit",
    ],
    pairs_well_with: [],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-brilliant/",
    active: true,
  },
  {
    id: "amex-delta-reserve",
    name: "Delta SkyMiles Reserve American Express Card",
    issuer: "American Express",
    network: "amex",
    country: "US",
    annual_fee: 650,
    rewards_program: "delta_skymiles",
    rewards_value_cpp: 1.2,
    earn_rates: { dining: 3, travel: 3, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 720,
    sign_up_bonus_spend: 6000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "Delta Sky Club access for cardholder when flying Delta (unlimited with $75k spend; otherwise 15 visits/yr)",
      "Companion Certificate for a domestic round-trip each anniversary",
      "3x miles on Delta purchases; MQD boost toward Medallion status",
      "First checked bag free; 20% back on Delta inflight purchases",
    ],
    pairs_well_with: ["amex-delta-platinum"],
    apply_url: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-reserve-american-express-card/",
    active: true,
  },
  {
    id: "capital-one-ventureone",
    name: "Capital One VentureOne Rewards",
    issuer: "Capital One",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "capital_one_miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.25, travel: 5, groceries: 1.25, streaming: 1.25, transit: 1.25, gas: 1.25, base: 1.25 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "1.25x miles on every purchase — no annual fee entry point into Capital One Miles",
      "5x miles on hotels and rental cars booked through Capital One Travel",
      "Transfer miles to 15+ airline and hotel partners",
      "No foreign transaction fees; 0% intro APR for 15 months on purchases",
    ],
    pairs_well_with: ["capital-one-venture-x"],
    apply_url: "https://capitalone.com/credit-cards/ventureone/",
    active: true,
  },
  {
    id: "capital-one-spark-miles",
    name: "Capital One Spark Miles for Business",
    issuer: "Capital One",
    network: "mastercard",
    country: "US",
    annual_fee: 95,
    rewards_program: "capital_one_miles",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 5, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 2 },
    sign_up_bonus_value: 500,
    sign_up_bonus_spend: 4500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: true,
    key_perks: [
      "2x miles on every purchase for business — simple, unlimited flat rate",
      "5x on hotels and rental cars via Capital One Travel",
      "Transfer miles to 15+ travel loyalty programs; Global Entry/TSA PreCheck credit",
      "Free employee cards; no foreign transaction fees",
    ],
    pairs_well_with: [],
    apply_url: "https://capitalone.com/small-business/credit-cards/spark-miles/",
    active: true,
  },
  {
    id: "citi-strata-premier",
    name: "Citi Strata Premier Card",
    issuer: "Citi",
    network: "mastercard",
    country: "US",
    annual_fee: 95,
    rewards_program: "points",
    rewards_value_cpp: 1.8,
    earn_rates: { dining: 3, travel: 3, groceries: 3, streaming: 1, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 600,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "3x ThankYou Points on air travel, hotels, restaurants, supermarkets, gas, and EV charging",
      "$100 annual hotel savings benefit on single hotel bookings of $500+ via thankyou.com",
      "Transfer points to 18 airline partners including JetBlue, Singapore Airlines, Turkish",
      "No foreign transaction fees; replaces and improves on Citi Premier",
    ],
    pairs_well_with: ["citi-double-cash", "citi-custom-cash"],
    apply_url: "https://www.citi.com/credit-cards/citi-strata-premier-credit-card",
    active: true,
  },
  {
    id: "citi-aadvantage-platinum-select",
    name: "Citi AAdvantage Platinum Select World Elite Mastercard",
    issuer: "Citi",
    network: "mastercard",
    country: "US",
    annual_fee: 99,
    rewards_program: "american_airlines_miles",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 2, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 2500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "First checked bag free for you and up to 4 companions on American Airlines flights",
      "2x miles on American Airlines, restaurants, and gas stations",
      "Preferred boarding on American flights; 25% discount on inflight food and drinks",
      "Annual fee waived first year; $125 American Airlines flight discount after $20k spend",
    ],
    pairs_well_with: [],
    apply_url: "https://www.citi.com/credit-cards/citi-aadvantage-platinum-select-mastercard",
    active: true,
  },
  {
    id: "bofa-travel-rewards",
    name: "Bank of America Travel Rewards Credit Card",
    issuer: "Bank of America",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.5, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 1.5 },
    sign_up_bonus_value: 250,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "1.5x points on every purchase — no annual fee, no foreign transaction fees",
      "Points redeemable as statement credit for any travel or dining purchase",
      "Preferred Rewards members earn 25–75% more points on every purchase",
      "No blackout dates or airline restrictions for redemption",
    ],
    pairs_well_with: ["bofa-premium-rewards"],
    apply_url: "https://www.bankofamerica.com/credit-cards/products/travel-rewards-credit-card/",
    active: true,
  },
  {
    id: "chase-amazon-prime",
    name: "Amazon Prime Rewards Visa Signature Card",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 2, groceries: 2, streaming: 1, transit: 1, gas: 2, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 0,
    foreign_transaction_fee: false,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "5% back at Amazon.com and Whole Foods Market (requires Prime membership)",
      "2% at restaurants, gas stations, and drugstores; 1% everywhere else",
      "No annual fee (Amazon Prime membership required, ~$139/yr)",
      "$200 Amazon gift card instantly upon approval",
    ],
    pairs_well_with: ["chase-freedom-unlimited"],
    apply_url: "https://www.amazon.com/Amazon-Prime-Rewards-Visa-Signature-Card/dp/BT00LN946S",
    active: true,
  },
  {
    id: "costco-anywhere-visa",
    name: "Costco Anywhere Visa Card by Citi",
    issuer: "Citi",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 3, groceries: 2, streaming: 1, transit: 1, gas: 4, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 0,
    foreign_transaction_fee: false,
    credit_score_minimum: 720,
    is_business: false,
    key_perks: [
      "4% on gas and EV charging (up to $7,000/yr then 1%); 3% on restaurants and travel",
      "2% on all Costco and Costco.com purchases",
      "No annual fee (Costco membership required, ~$65/yr)",
      "Cash rewards distributed annually as a certificate redeemable at Costco",
    ],
    pairs_well_with: [],
    apply_url: "https://www.citi.com/credit-cards/costco-anywhere-visa-credit-card-by-citi",
    active: true,
  },
  {
    id: "wells-fargo-reflect",
    name: "Wells Fargo Reflect Card",
    issuer: "Wells Fargo",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 0,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "0% intro APR for 21 months on purchases and qualifying balance transfers — best in class",
      "No annual fee; cell phone protection up to $600 per claim",
      "Ideal for carrying a balance interest-free or financing a large purchase",
      "My Wells Fargo Deals: earn cash back via Autograph Rewards partner offers",
    ],
    pairs_well_with: ["wells-fargo-active-cash"],
    apply_url: "https://www.wellsfargo.com/credit-cards/reflect/",
    active: true,
  },
  {
    id: "barclays-aadvantage-aviator-red",
    name: "AAdvantage Aviator Red World Elite Mastercard",
    issuer: "Barclays",
    network: "mastercard",
    country: "US",
    annual_fee: 99,
    rewards_program: "american_airlines_miles",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 2, travel: 2, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Earn 60,000 miles after first purchase and paying annual fee — no minimum spend required",
      "First checked bag free on American Airlines for you and up to 4 companions",
      "2x miles on eligible American Airlines purchases; 1x on everything else",
      "Preferred boarding; $25 inflight WiFi credit per anniversary year",
    ],
    pairs_well_with: [],
    apply_url: "https://cards.barclaycardus.com/banking/cards/aadvantage-aviator-red-world-elite-mastercard/",
    active: true,
  },
  {
    id: "us-bank-shopper-cash-rewards",
    name: "U.S. Bank Shopper Cash Rewards Visa Signature",
    issuer: "U.S. Bank",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1.5, travel: 1.5, groceries: 1.5, streaming: 6, transit: 1.5, gas: 1.5, base: 1.5 },
    sign_up_bonus_value: 250,
    sign_up_bonus_spend: 2000,
    sign_up_bonus_days: 120,
    foreign_transaction_fee: true,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "6% cash back at two retailers you choose each quarter (Target, Amazon, Walmart, etc.)",
      "3% on one everyday category you choose (grocery, gas, dining, streaming, or EV charging)",
      "1.5% on all other purchases; $25 annual fee credit for eligible purchases",
      "Quarterly enrollment required; ideal for loyal big-box shoppers",
    ],
    pairs_well_with: [],
    apply_url: "https://www.usbank.com/credit-cards/shopper-cash-rewards-visa-credit-card.html",
    active: true,
  },
  {
    id: "petal-2-visa",
    name: "Petal 2 Visa Credit Card",
    issuer: "WebBank",
    network: "visa",
    country: "US",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 1.0 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 0,
    foreign_transaction_fee: false,
    credit_score_minimum: 580,
    is_business: false,
    key_perks: [
      "No annual fee, no foreign transaction fees — designed for building or rebuilding credit",
      "Up to 10% cash back at select local merchants; 1.5% base after 12 on-time payments",
      "No credit history required — approval uses bank account data if no credit file",
      "Credit limits from $300 to $10,000; reports to all 3 major bureaus",
    ],
    pairs_well_with: [],
    apply_url: "https://www.petalcard.com/",
    active: true,
  },
  {
    id: "chase-british-airways-visa",
    name: "British Airways Visa Signature Card",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "avios",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 3, travel: 3, groceries: 1, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 375,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "3x Avios on British Airways, Iberia, Aer Lingus, and LEVEL purchases",
      "Travel Together Ticket when you spend $30k/year — companion on any BA route",
      "Avios transfer 1:1 to American Airlines AAdvantage for domestic redemptions",
      "10% discount on British Airways flights departing from the U.S.",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/british-airways",
    active: true,
  },
  {
    id: "chase-aeroplan",
    name: "Aeroplan Credit Card",
    issuer: "Chase",
    network: "visa",
    country: "US",
    annual_fee: 95,
    rewards_program: "aeroplan",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 3, travel: 3, groceries: 3, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 750,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "3x points on dining, groceries, and Air Canada purchases",
      "Free first checked bag on Air Canada for you and up to 8 companions",
      "Preferred pricing on Aeroplan award flights; 500 bonus points per flight segment",
      "Transfer to United MileagePlus and other Star Alliance partners 1:1",
    ],
    pairs_well_with: ["chase-sapphire-preferred"],
    apply_url: "https://creditcards.chase.com/travel-credit-cards/united/aeroplan",
    active: true,
  },

  // ── ADDITIONAL CANADIAN CARDS ──────────────────────────────────────────────
  {
    id: "scotiabank-gold-amex-ca",
    name: "Scotiabank Gold American Express Card",
    issuer: "Scotiabank",
    network: "amex",
    country: "CA",
    annual_fee: 120,
    rewards_program: "scene_plus",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 6, travel: 5, groceries: 6, streaming: 3, transit: 3, gas: 3, base: 1 },
    sign_up_bonus_value: 450,
    sign_up_bonus_spend: 7500,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "6x Scene+ points on groceries and dining — one of the best food-spend rates in Canada",
      "No foreign transaction fees — rare for a Canadian credit card",
      "5x points on other eligible travel; 3x on entertainment, transit, and streaming",
      "Comprehensive travel insurance package including emergency medical",
    ],
    pairs_well_with: ["scotia-passport-visa-ca"],
    apply_url: "https://www.scotiabank.com/ca/en/personal/credit-cards/american-express/gold-card.html",
    active: true,
  },
  {
    id: "scotiabank-scene-plus-visa-ca",
    name: "Scotiabank Scene+ Visa Card",
    issuer: "Scotiabank",
    network: "visa",
    country: "CA",
    annual_fee: 0,
    rewards_program: "scene_plus",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 5, travel: 3, groceries: 3, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 100,
    sign_up_bonus_spend: 500,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 650,
    is_business: false,
    key_perks: [
      "5x Scene+ points at Sobeys, Safeway, IGA, and other participating grocery stores",
      "3x points at other grocery stores and on eligible travel purchases",
      "No annual fee; Scene+ points redeemable for movies, travel, gift cards, and more",
      "Easy approval — good entry-level card for Scene+ ecosystem",
    ],
    pairs_well_with: ["scotiabank-gold-amex-ca"],
    apply_url: "https://www.scotiabank.com/ca/en/personal/credit-cards/visa/scene-plus-card.html",
    active: true,
  },
  {
    id: "cibc-aeroplan-visa-infinite-ca",
    name: "CIBC Aeroplan Visa Infinite Card",
    issuer: "CIBC",
    network: "visa",
    country: "CA",
    annual_fee: 139,
    rewards_program: "aeroplan",
    rewards_value_cpp: 1.5,
    earn_rates: { dining: 2, travel: 3, groceries: 3, streaming: 1, transit: 1, gas: 1.5, base: 1 },
    sign_up_bonus_value: 450,
    sign_up_bonus_spend: 4000,
    sign_up_bonus_days: 180,
    foreign_transaction_fee: true,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "Free first checked bag on Air Canada for the primary cardholder",
      "3x Aeroplan points on groceries and Air Canada purchases; 1.5x on gas",
      "Preferred pricing on Aeroplan award tickets; complimentary Aeroplan status boost",
      "Comprehensive travel and purchase protection insurance",
    ],
    pairs_well_with: ["td-aeroplan-infinite-ca"],
    apply_url: "https://www.cibc.com/en/personal-banking/credit-cards/aeroplan/visa-infinite.html",
    active: true,
  },
  {
    id: "tangerine-money-back-ca",
    name: "Tangerine Money-Back Credit Card",
    issuer: "Tangerine",
    network: "mastercard",
    country: "CA",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 2, travel: 1, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 0.5 },
    sign_up_bonus_value: 100,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 600,
    is_business: false,
    key_perks: [
      "2% cash back in up to 3 categories you choose (groceries, gas, dining, transit, etc.)",
      "No annual fee — deposit rewards directly to Tangerine Savings for automatic saving",
      "0.5% unlimited cash back on everything else",
      "Simple approval; no income requirement published",
    ],
    pairs_well_with: [],
    apply_url: "https://www.tangerine.ca/en/personal/bank/creditcards/money-back/",
    active: true,
  },
  {
    id: "simplii-cash-back-visa-ca",
    name: "Simplii Financial Cash Back Visa Card",
    issuer: "Simplii Financial",
    network: "visa",
    country: "CA",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 4, travel: 1.5, groceries: 1.5, streaming: 1.5, transit: 1.5, gas: 1.5, base: 0.5 },
    sign_up_bonus_value: 100,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 650,
    is_business: false,
    key_perks: [
      "4% cash back on eligible restaurant, bar, and coffee shop purchases (up to $5,000/yr)",
      "1.5% on groceries, gas, drug stores, and pre-authorized payments",
      "No annual fee; one of Canada's best no-fee dining cards",
      "0.5% unlimited cash back on everything else",
    ],
    pairs_well_with: [],
    apply_url: "https://www.simplii.com/en/credit-cards/cash-back-visa-card.html",
    active: true,
  },
  {
    id: "pc-financial-world-elite-ca",
    name: "PC Financial World Elite Mastercard",
    issuer: "PC Financial",
    network: "mastercard",
    country: "CA",
    annual_fee: 0,
    rewards_program: "pc_optimum",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 1, groceries: 4.5, streaming: 1, transit: 1, gas: 3, base: 1 },
    sign_up_bonus_value: 150,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "45 PC Optimum points per $1 at Loblaw stores (Loblaws, Real Canadian Superstore, No Frills)",
      "30 points per $1 at Shoppers Drug Mart; 10 points per $1 everywhere else",
      "No annual fee — exceptional grocery rewards for Loblaw shoppers",
      "Annual income requirement: $80k personal or $150k household",
    ],
    pairs_well_with: [],
    apply_url: "https://www.pcfinancial.ca/en/credit-cards/world-elite-mastercard/",
    active: true,
  },
  {
    id: "bmo-cashback-world-elite-ca",
    name: "BMO CashBack World Elite Mastercard",
    issuer: "BMO",
    network: "mastercard",
    country: "CA",
    annual_fee: 120,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 2, groceries: 5, streaming: 2, transit: 2, gas: 4, base: 1 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "5% cash back on groceries — highest grocery rate of any major Canadian card",
      "4% on transit, 3% on gas, 2% on recurring bills and travel purchases",
      "$150 first-year annual fee rebate available; comprehensive travel insurance",
      "World Elite Mastercard benefits including Mastercard Travel Pass lounge access (DragonPass)",
    ],
    pairs_well_with: ["tangerine-money-back-ca"],
    apply_url: "https://www.bmo.com/main/personal/credit-cards/bmo-cashback-world-elite-mastercard/",
    active: true,
  },
  {
    id: "td-first-class-travel-visa-ca",
    name: "TD First Class Travel Visa Infinite Card",
    issuer: "TD",
    network: "visa",
    country: "CA",
    annual_fee: 139,
    rewards_program: "td_rewards",
    rewards_value_cpp: 0.5,
    earn_rates: { dining: 8, travel: 8, groceries: 4, streaming: 4, transit: 4, gas: 4, base: 2 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "8x TD Rewards points on travel booked via Expedia for TD; 4x on groceries and dining",
      "Redeem points flexibly through Expedia for TD or as statement credits for any travel",
      "Comprehensive travel insurance including emergency medical up to $2M",
      "Annual birthday bonus of 10% of points earned in the prior year",
    ],
    pairs_well_with: ["td-aeroplan-infinite-ca"],
    apply_url: "https://www.td.com/ca/en/personal-banking/products/credit-cards/travel/first-class-travel-visa-infinite-card/",
    active: true,
  },
  {
    id: "hsbc-world-elite-ca",
    name: "HSBC World Elite Mastercard",
    issuer: "HSBC",
    network: "mastercard",
    country: "CA",
    annual_fee: 149,
    rewards_program: "points",
    rewards_value_cpp: 0.5,
    earn_rates: { dining: 6, travel: 6, groceries: 3, streaming: 3, transit: 3, gas: 3, base: 3 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "No foreign transaction fees — rare at this fee level in Canada",
      "$100 annual travel enhancement credit; $30 annual global Wi-Fi credit",
      "6 points per $1 on travel and dining; 3 points on all other eligible purchases",
      "LoungeKey airport lounge access; comprehensive travel and purchase protection",
    ],
    pairs_well_with: [],
    apply_url: "https://www.hsbc.ca/credit-cards/products/world-elite/",
    active: true,
  },
  {
    id: "amex-simplycash-preferred-ca",
    name: "American Express SimplyCash Preferred Card",
    issuer: "American Express",
    network: "amex",
    country: "CA",
    annual_fee: 99,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 4, travel: 2, groceries: 4, streaming: 2, transit: 2, gas: 4, base: 2 },
    sign_up_bonus_value: 400,
    sign_up_bonus_spend: 3000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: true,
    credit_score_minimum: 670,
    is_business: false,
    key_perks: [
      "4% cash back on gas, groceries, and drugstores — no cap on eligible spend",
      "2% unlimited cash back on all other purchases",
      "Comprehensive purchase and travel insurance included",
      "Amex Offers for additional savings at select merchants",
    ],
    pairs_well_with: ["scotiabank-gold-amex-ca"],
    apply_url: "https://www.americanexpress.com/en-ca/credit-cards/simplycash-preferred/",
    active: true,
  },
  {
    id: "rbc-cashback-mastercard-ca",
    name: "RBC Cash Back Mastercard",
    issuer: "RBC",
    network: "mastercard",
    country: "CA",
    annual_fee: 0,
    rewards_program: "cash_back",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 1, travel: 1, groceries: 2, streaming: 1, transit: 1, gas: 1, base: 1 },
    sign_up_bonus_value: 0,
    sign_up_bonus_spend: 0,
    sign_up_bonus_days: 0,
    foreign_transaction_fee: true,
    credit_score_minimum: 600,
    is_business: false,
    key_perks: [
      "2% cash back at grocery stores; 1% on all other eligible purchases",
      "No annual fee — solid no-fee starter card for RBC customers",
      "Cash back applied as a credit to your statement",
      "Optional credit card payment insurance available",
    ],
    pairs_well_with: ["rbc-avion-visa-infinite-ca"],
    apply_url: "https://www.rbc.com/creditcards/cashback-mastercard.html",
    active: true,
  },
  {
    id: "desjardins-odyssey-world-elite-ca",
    name: "Desjardins Odyssey World Elite Mastercard",
    issuer: "Desjardins",
    network: "mastercard",
    country: "CA",
    annual_fee: 130,
    rewards_program: "points",
    rewards_value_cpp: 1.0,
    earn_rates: { dining: 3, travel: 3, groceries: 2, streaming: 2, transit: 2, gas: 2, base: 1.5 },
    sign_up_bonus_value: 200,
    sign_up_bonus_spend: 1000,
    sign_up_bonus_days: 90,
    foreign_transaction_fee: false,
    credit_score_minimum: 700,
    is_business: false,
    key_perks: [
      "No foreign transaction fees; strong travel insurance package",
      "Priority Pass lounge access for cardholder and authorized users",
      "3x BONUSDOLLARS on travel and dining; 2x on groceries and gas",
      "Best for Quebec residents in the Desjardins banking ecosystem",
    ],
    pairs_well_with: [],
    apply_url: "https://www.desjardins.com/en/personal/accounts-services/credit-cards/odyssey-world-elite.html",
    active: true,
  },
];

async function seed() {
  const db = getSupabaseAdmin();
  console.log(`Seeding ${CARDS.length} credit cards...`);

  const { error } = await db
    .from("credit_cards")
    .upsert(CARDS, { onConflict: "id" });

  if (error) {
    console.error("Seed failed:", error.message);
    process.exit(1);
  }

  console.log(`Successfully seeded ${CARDS.length} cards.`);
}

seed();
